// lidar_relay_node.cpp
//
// Subscribes  : /shelfbot_firmware/laser_scan  (sensor_msgs/LaserScan, RELIABLE)
//               Complete revolution published by the firmware once per full
//               lidar rotation.
//
// Publishes   : /scan  (sensor_msgs/LaserScan, BEST_EFFORT / SensorDataQoS)
//               The original firmware timestamp is PRESERVED. Only the
//               frame_id is rewritten to 'laser_link'.
//
// WHY PRESERVE THE FIRMWARE TIMESTAMP:
//   The firmware timestamp is generated by an SNTP‑synchronised clock on the
//   ESP32. The laptop's ROS clock (use_sim_time=false) is also NTP‑synced to
//   the same time source. Therefore, the timestamps are already in the same
//   time domain. Re‑stamping would break this alignment and cause TF lookups
//   to fail (as they rely on the timestamp matching the transform cache).
//
//   If timestamps are still mismatched, ensure both the laptop and the ESP32
//   are synchronised to the same NTP server.

#include <rclcpp/rclcpp.hpp>
#include <sensor_msgs/msg/laser_scan.hpp>

static constexpr const char* LOG_TAG = "LidarRelay";

class LidarRelayNode : public rclcpp::Node {
public:
    LidarRelayNode() : Node("lidar_relay_node") {

        declare_parameter<std::string>("frame_id", "laser_link");
        frame_id_ = get_parameter("frame_id").as_string();

        // ── Subscriber ────────────────────────────────────────────────────
        // Firmware publishes RELIABLE; match it.
        auto sub_qos = rclcpp::QoS(rclcpp::KeepLast(10)).reliable();
        sub_ = create_subscription<sensor_msgs::msg::LaserScan>(
            "/shelfbot_firmware/laser_scan",
            sub_qos,
            [this](sensor_msgs::msg::LaserScan::SharedPtr msg) {
                on_scan(std::move(msg));
            });

        // ── Publisher ─────────────────────────────────────────────────────
        // Use RELIABLE to be compatible with ALL subscribers (BEST_EFFORT + RELIABLE).
        // This matches Nav2's default costmap QoS and still works with slam_toolbox.
        pub_ = create_publisher<sensor_msgs::msg::LaserScan>(
            "/scan", rclcpp::SystemDefaultsQoS());   // RELIABLE, KeepLast(10), Volatile durability

        RCLCPP_INFO(get_logger(),
            "[%s] relay /shelfbot_firmware/laser_scan (RELIABLE) "
            "→ /scan (RELIABLE)  frame_id='%s'  timestamp preserved",
            LOG_TAG, frame_id_.c_str());
    }

private:
    void on_scan(sensor_msgs::msg::LaserScan::SharedPtr msg) {

        // Preserve the firmware's original timestamp; only change frame_id.
        msg->header.frame_id = frame_id_;

        if (!first_received_) {
            first_received_ = true;
            RCLCPP_INFO(get_logger(),
                "[%s] First scan: %zu ranges  "
                "angle_min=%.3f  angle_max=%.3f  "
                "range_min=%.3f m  range_max=%.3f m  "
                "firmware_stamp=%d.%09d  frame_id='%s'",
                LOG_TAG,
                msg->ranges.size(),
                msg->angle_min, msg->angle_max,
                msg->range_min, msg->range_max,
                msg->header.stamp.sec, msg->header.stamp.nanosec,
                msg->header.frame_id.c_str());
        }

        pub_->publish(std::move(*msg));
    }

    rclcpp::Subscription<sensor_msgs::msg::LaserScan>::SharedPtr sub_;
    rclcpp::Publisher<sensor_msgs::msg::LaserScan>::SharedPtr    pub_;
    std::string frame_id_;
    bool        first_received_ = false;
};

int main(int argc, char** argv) {
    rclcpp::init(argc, argv);
    rclcpp::spin(std::make_shared<LidarRelayNode>());
    rclcpp::shutdown();
    return 0;
}