// lidar_relay_node.cpp
//
// Subscribes  : /shelfbot_firmware/laser_scan  (sensor_msgs/LaserScan, RELIABLE)
//               Complete revolution published by the firmware once per full
//               lidar rotation.
//
// Publishes   : /scan  (sensor_msgs/LaserScan, RELIABLE)
//               The original firmware timestamp is PRESERVED.  The frame_id is
//               rewritten to 'laser_link' and, by default, scan ordering is
//               mirrored into ROS LaserScan coordinates.
//
// WHY REVERSE THE FIRMWARE SCAN ORDER:
//   The ESP32 firmware decodes LYDSTO packet angles in the sensor's native
//   increasing-angle order.  On this hardware that order is clockwise when
//   viewed from +Z, while ROS LaserScan uses a right-handed frame: angle 0 is
//   +X and positive angles rotate counter-clockwise toward +Y.  A static TF yaw
//   can rotate a scan, but it cannot fix a clockwise/counter-clockwise mirror.
//   Therefore the relay reverses the range/intensity arrays and negates the
//   angle bounds before publishing /scan.
//
// WHY PRESERVE THE FIRMWARE TIMESTAMP:
//   The firmware timestamp is generated by an SNTP-synchronised clock on the
//   ESP32. The laptop's ROS clock (use_sim_time=false) is also NTP-synced to
//   the same time source. Therefore, the timestamps are already in the same
//   time domain. Re-stamping would break this alignment and cause TF lookups
//   to fail (as they rely on the timestamp matching the transform cache).
//
//   If timestamps are still mismatched, ensure both the laptop and the ESP32
//   are synchronised to the same NTP server.

#include <algorithm>
#include <cmath>
#include <string>

#include <rclcpp/rclcpp.hpp>
#include <sensor_msgs/msg/laser_scan.hpp>

static constexpr const char* LOG_TAG = "LidarRelay";

class LidarRelayNode : public rclcpp::Node {
public:
    LidarRelayNode() : Node("lidar_relay_node") {

        declare_parameter<std::string>("frame_id", "laser_link");
        declare_parameter<bool>("reverse_scan_order", true);
        frame_id_ = get_parameter("frame_id").as_string();
        reverse_scan_order_ = get_parameter("reverse_scan_order").as_bool();

        // ── Subscriber ────────────────────────────────────────────────────
        // Firmware publishes RELIABLE; match it.
        auto sub_qos = rclcpp::QoS(rclcpp::KeepLast(10)).reliable();
        sub_ = create_subscription<sensor_msgs::msg::LaserScan>(
            "/shelfbot_firmware/laser_scan",
            sub_qos,
            [this](sensor_msgs::msg::LaserScan::SharedPtr msg) {
                on_scan(std::move(msg));
            });

        // ── Publisher ─────────────────────────────────────────────────────
        // Use RELIABLE to be compatible with ALL subscribers (BEST_EFFORT + RELIABLE).
        // This matches Nav2's default costmap QoS and still works with slam_toolbox.
        pub_ = create_publisher<sensor_msgs::msg::LaserScan>("/scan", rclcpp::SystemDefaultsQoS());

        RCLCPP_INFO(get_logger(),
            "[%s] relay /shelfbot_firmware/laser_scan (RELIABLE) → /scan "
            "(RELIABLE) frame_id='%s' reverse_scan_order=%s timestamp preserved",
            LOG_TAG, frame_id_.c_str(), reverse_scan_order_ ? "true" : "false");
    }

private:
    void on_scan(sensor_msgs::msg::LaserScan::SharedPtr msg) {
        // Preserve the firmware's original timestamp; change frame_id and, if
        // configured, mirror the native clockwise scan into ROS CCW ordering.
        msg->header.frame_id = frame_id_;

        if (reverse_scan_order_) {
            normalize_clockwise_scan(*msg);
        }

        if (!first_received_) {
            first_received_ = true;
            RCLCPP_INFO(get_logger(),
                "[%s] First scan: %zu ranges  "
                "angle_min=%.3f  angle_max=%.3f  angle_increment=%.6f  "
                "range_min=%.3f m  range_max=%.3f m  "
                "firmware_stamp=%d.%09d  frame_id='%s'  reverse_scan_order=%s",
                LOG_TAG,
                msg->ranges.size(),
                msg->angle_min, msg->angle_max, msg->angle_increment,
                msg->range_min, msg->range_max,
                msg->header.stamp.sec, msg->header.stamp.nanosec,
                msg->header.frame_id.c_str(),
                reverse_scan_order_ ? "true" : "false");
        }

        pub_->publish(std::move(*msg));
    }

    static void normalize_clockwise_scan(sensor_msgs::msg::LaserScan& scan) {
        if (scan.ranges.empty()) {
            return;
        }

        std::reverse(scan.ranges.begin(), scan.ranges.end());
        std::reverse(scan.intensities.begin(), scan.intensities.end());

        const float old_angle_min = scan.angle_min;
        const float old_angle_max = scan.angle_max;

        // Firmware/native angle +θ is clockwise; ROS +θ must be CCW.  After
        // reversing samples, negate the angular interval and keep angle_min <
        // angle_max with a positive increment for consumers that assume that
        // common LaserScan layout.
        scan.angle_min = -old_angle_max;
        scan.angle_max = -old_angle_min;
        scan.angle_increment = std::abs(scan.angle_increment);
    }

    rclcpp::Subscription<sensor_msgs::msg::LaserScan>::SharedPtr sub_;
    rclcpp::Publisher<sensor_msgs::msg::LaserScan>::SharedPtr    pub_;
    std::string frame_id_;
    bool        reverse_scan_order_ = true;
    bool        first_received_ = false;
};

int main(int argc, char** argv) {
    rclcpp::init(argc, argv);
    rclcpp::spin(std::make_shared<LidarRelayNode>());
    rclcpp::shutdown();
    return 0;
}
