<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="base_axis" params="name length radius">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <origin xyz="${length/2} 0 0" rpy="0 ${pi/2} 0"/>
        <material name="dark_red"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <origin xyz="${length/2} 0 0" rpy="0 ${pi/2} 0"/>
      </collision>
      <inertial>
        <mass value="${base_axis_mass}"/>
        <origin xyz="${length/2} 0 0" rpy="0 ${pi/2} 0"/>
        <xacro:cylinder_inertia m="${base_axis_mass}" r="${radius}" h="${length}"/>
      </inertial>
    </link>
  </xacro:macro>
</robot>
