<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <material name="golden_brown">
    <color rgba="0.87 0.72 0.53 1.0"/>
  </material>
  <material name="metallic_dark_lead">
    <color rgba="0.33 0.33 0.33 1.0"/>
  </material>
  <material name="dark_red">
    <color rgba="0.55 0.0 0.0 1.0"/>
  </material>
  <material name="metallic_gray">
    <color rgba="0.66 0.66 0.66 1.0"/>
  </material>
  <material name="red">
    <color rgba="1.0 0.0 0.0 1.0"/>
  </material>

  <xacro:property name="base_width" value="0.5"/>
  <xacro:property name="base_length" value="0.7"/>
  <xacro:property name="base_height" value="0.2"/>
  <xacro:property name="base_mass" value="50.0"/>

  <xacro:property name="motor_radius" value="0.05"/>
  <xacro:property name="motor_length" value="0.2"/>
  <xacro:property name="motor_mass" value="2.0"/>

  <xacro:property name="wheel_radius" value="0.2"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_mass" value="5.0"/>

  <xacro:property name="camera_width" value="0.2"/>
  <xacro:property name="camera_length" value="0.2"/>
  <xacro:property name="camera_height" value="0.1"/>
  <xacro:property name="camera_lens_radius" value="0.05"/>
  <xacro:property name="camera_mount_height" value="0.5"/>
  <xacro:property name="camera_mass" value="0.5"/>

  <xacro:property name="base_axis_radius" value="0.02"/>
  <xacro:property name="base_axis_length" value="${motor_length + wheel_width}"/>
  <xacro:property name="base_axis_mass" value="1.0"/>

  <xacro:property name="gear_ratio" value="2"/>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
             iyy="${m*(3*r*r+h*h)/12}" iyz="0"
             izz="${m*r*r/2}"/>
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
             iyy="${m*(x*x+z*z)/12}" iyz="0"
             izz="${m*(x*x+y*y)/12}"/>
  </xacro:macro>
</robot>
