<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="gazebo_link_properties" params="link color">
    <gazebo reference="${link}">
      <material>Gazebo/${color}</material>
      <mu1>0.2</mu1>
      <mu2>0.2</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <maxVel>1.0</maxVel>
      <minDepth>0.001</minDepth>
    </gazebo>
  </xacro:macro>

  <!-- Apply properties to links -->
  <xacro:gazebo_link_properties link="base_link" color="Gold"/>
  <xacro:gazebo_link_properties link="wheel_front_left" color="Black"/>
  <xacro:gazebo_link_properties link="wheel_front_right" color="Black"/>
  <xacro:gazebo_link_properties link="wheel_back_left" color="Black"/>
  <xacro:gazebo_link_properties link="wheel_back_right" color="Black"/>
  <xacro:gazebo_link_properties link="base_axis_front_left" color="Red"/>
  <xacro:gazebo_link_properties link="base_axis_front_right" color="Red"/>
  <xacro:gazebo_link_properties link="base_axis_back_left" color="Red"/>
  <xacro:gazebo_link_properties link="base_axis_back_right" color="Red"/>
  <xacro:gazebo_link_properties link="motor_front_left" color="Grey"/>
  <xacro:gazebo_link_properties link="motor_front_right" color="Grey"/>
  <xacro:gazebo_link_properties link="motor_back_left" color="Grey"/>
  <xacro:gazebo_link_properties link="motor_back_right" color="Grey"/>
  <xacro:gazebo_link_properties link="camera" color="Blue"/>

  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <updateRate>100.0</updateRate>
      <leftJoint>joint_wheel_front_left</leftJoint>
      <rightJoint>joint_wheel_front_right</rightJoint>
      <wheelSeparation>${base_width}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <robotBaseFrame>base_link</robotBaseFrame>
      <publishWheelTF>true</publishWheelTF>
      <publishOdomTF>true</publishOdomTF>
      <publishWheelJointState>true</publishWheelJointState>
      <odometrySource>world</odometrySource>
    </plugin>
  </gazebo>

  <gazebo reference="camera">
    <sensor type="camera" name="camera">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>600</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>shelfbot/camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera</frameName>
      </plugin>
    </sensor>
  </gazebo>

</robot>
