<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Gazebo colors for each link -->
  <gazebo reference="base_link">
    <material>Gazebo/Gold</material>
  </gazebo>

  <gazebo reference="wheel_front_left">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="wheel_front_right">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="wheel_back_left">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="wheel_back_right">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="base_axis_front_left">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="base_axis_front_right">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="base_axis_back_left">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="base_axis_back_right">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="motor_front_left">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="motor_front_right">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="motor_back_left">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="motor_back_right">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="camera">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Gazebo plugin for 4-wheeled robot control -->
  <gazebo>
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <updateRate>100.0</updateRate>
      <robotNamespace>/</robotNamespace>
      <leftFrontJoint>joint_base_axis_front_left</leftFrontJoint>
      <rightFrontJoint>joint_base_axis_front_right</rightFrontJoint>
      <leftRearJoint>joint_base_axis_back_left</leftRearJoint>
      <rightRearJoint>joint_base_axis_back_right</rightRearJoint>
      <wheelSeparation>${base_width}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <robotBaseFrame>base_link</robotBaseFrame>
      <torque>20</torque>
      <topicName>cmd_vel</topicName>
      <broadcastTF>true</broadcastTF>
    </plugin>
  </gazebo>

  <gazebo reference="camera">
    <sensor type="camera" name="camera">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>600</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>shelfbot/camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera</frameName>
      </plugin>
    </sensor>
  </gazebo>

</robot>