<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="shelfbot">

  <xacro:include filename="$(find shelfbot)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/motor.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/wheel.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/camera.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/base_axis.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/gazebo.urdf.xacro"/>

  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
      <material name="golden_brown"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5"/>
      <inertia ixx="0.0395" ixy="0" ixz="0" iyy="0.086" iyz="0" izz="0.0754"/>
    </inertial>
  </link>

  <joint name="joint_base_footprint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_height / 2 + wheel_radius}" rpy="0 0 0"/>
  </joint>

  <xacro:base_axis name="base_axis_front_left" length="${base_axis_length}" radius="${base_axis_radius}"/>
  <xacro:base_axis name="base_axis_front_right" length="${base_axis_length}" radius="${base_axis_radius}"/>
  <xacro:base_axis name="base_axis_back_left" length="${base_axis_length}" radius="${base_axis_radius}"/>
  <xacro:base_axis name="base_axis_back_right" length="${base_axis_length}" radius="${base_axis_radius}"/>

  <xacro:motor name="motor_front_left" length="${motor_length}" radius="${motor_radius}" mass="1.0" ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
  <xacro:motor name="motor_front_right" length="${motor_length}" radius="${motor_radius}" mass="1.0" ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
  <xacro:motor name="motor_back_left" length="${motor_length}" radius="${motor_radius}" mass="1.0" ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
  <xacro:motor name="motor_back_right" length="${motor_length}" radius="${motor_radius}" mass="1.0" ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>

  <xacro:wheel name="wheel_front_left" radius="${wheel_radius}" width="${wheel_width}"/>
  <xacro:wheel name="wheel_front_right" radius="${wheel_radius}" width="${wheel_width}"/>
  <xacro:wheel name="wheel_back_left" radius="${wheel_radius}" width="${wheel_width}"/>
  <xacro:wheel name="wheel_back_right" radius="${wheel_radius}" width="${wheel_width}"/>

  <joint name="joint_motor_front_left" type="fixed">
    <parent link="base_link"/>
    <child link="motor_front_left"/>
    <origin xyz="${-base_width / 2} ${base_length / 2} 0" rpy="0 ${pi/2} 0"/>
  </joint>

  <joint name="joint_motor_front_right" type="fixed">
    <parent link="base_link"/>
    <child link="motor_front_right"/>
    <origin xyz="${base_width / 2} ${base_length / 2} 0" rpy="0 ${pi/2} 0"/>
  </joint>

  <joint name="joint_motor_back_left" type="fixed">
    <parent link="base_link"/>
    <child link="motor_back_left"/>
    <origin xyz="${-base_width / 2} ${-base_length / 2} 0" rpy="0 ${pi/2} 0"/>
  </joint>

  <joint name="joint_motor_back_right" type="fixed">
    <parent link="base_link"/>
    <child link="motor_back_right"/>
    <origin xyz="${base_width / 2} ${-base_length / 2} 0" rpy="0 ${pi/2} 0"/>
  </joint>

  <joint name="joint_base_axis_front_left" type="continuous">
    <parent link="motor_front_left"/>
    <child link="base_axis_front_left"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" velocity="10"/>
  </joint>

  <joint name="joint_base_axis_front_right" type="continuous">
    <parent link="motor_front_right"/>
    <child link="base_axis_front_right"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" velocity="10"/>
  </joint>

  <joint name="joint_base_axis_back_left" type="continuous">
    <parent link="motor_back_left"/>
    <child link="base_axis_back_left"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" velocity="10"/>
  </joint>

  <joint name="joint_base_axis_back_right" type="continuous">
    <parent link="motor_back_right"/>
    <child link="base_axis_back_right"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" velocity="10"/>
  </joint>

  <joint name="joint_wheel_front_left" type="fixed">
    <parent link="base_axis_front_left"/>
    <child link="wheel_front_left"/>
    <origin xyz="0 0 -${motor_length/2}" rpy="0 0 0"/>
  </joint>

  <joint name="joint_wheel_front_right" type="fixed">
    <parent link="base_axis_front_right"/>
    <child link="wheel_front_right"/>
    <origin xyz="0 0 ${motor_length/2}" rpy="0 0 0"/>
  </joint>

  <joint name="joint_wheel_back_left" type="fixed">
    <parent link="base_axis_back_left"/>
    <child link="wheel_back_left"/>
    <origin xyz="0 0 -${motor_length/2}" rpy="0 0 0"/>
  </joint>

  <joint name="joint_wheel_back_right" type="fixed">
    <parent link="base_axis_back_right"/>
    <child link="wheel_back_right"/>
    <origin xyz="0 0 ${motor_length/2}" rpy="0 0 0"/>
  </joint>

  <xacro:camera name="camera" width="${camera_width}" length="${camera_length}" height="${camera_height}" radius="${camera_lens_radius}"/>

  <joint name="joint_camera" type="fixed">
    <parent link="base_link"/>
    <child link="camera"/>
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
  </joint>

  <ros2_control name="FourWheelDriveSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="joint_base_axis_front_left">
      <command_interface name="position"/>
      <state_interface name="position"/>
    </joint>
    <joint name="joint_base_axis_front_right">
      <command_interface name="position"/>
      <state_interface name="position"/>
    </joint>
    <joint name="joint_base_axis_back_left">
      <command_interface name="position"/>
      <state_interface name="position"/>
    </joint>
    <joint name="joint_base_axis_back_right">
      <command_interface name="position"/>
      <state_interface name="position"/>
    </joint>
  </ros2_control>
</robot>
