<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="shelfbot">

  <xacro:include filename="$(find shelfbot)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/motor.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/wheel.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/camera.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/base_axis.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/box.xacro"/>

  <xacro:arg name="sim_mode" default="gazebo"/>
  
  <xacro:if value="${'$(arg sim_mode)' == 'gazebo'}">
    <xacro:include filename="$(find shelfbot)/urdf/gazebo.urdf.xacro"/>
  </xacro:if>
  
  <xacro:if value="${'$(arg sim_mode)' == 'isaac'}">
    <xacro:include filename="$(find shelfbot)/urdf/isaac.sim.urdf.xacro"/>
  </xacro:if>
  
  <xacro:if value="${'$(arg sim_mode)' == 'real'}">
    <xacro:include filename="$(find shelfbot)/urdf/real.robot.urdf.xacro"/>
  </xacro:if>
  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
      <material name="golden_brown"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <xacro:box_inertia m="${base_mass}" x="${base_width}" y="${base_length}" z="${base_height}"/>
    </inertial>
  </link>

  <joint name="joint_base_footprint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_height / 2 + wheel_radius}" rpy="0 0 0"/>
  </joint>

  <xacro:motor name="motor_front_left" length="${motor_length}" radius="${motor_radius}"/>
  <xacro:motor name="motor_front_right" length="${motor_length}" radius="${motor_radius}"/>
  <xacro:motor name="motor_back_left" length="${motor_length}" radius="${motor_radius}"/>
  <xacro:motor name="motor_back_right" length="${motor_length}" radius="${motor_radius}"/>

  <xacro:base_axis name="base_axis_front_left" length="${base_axis_length}" radius="${base_axis_radius}"/>
  <xacro:base_axis name="base_axis_front_right" length="${base_axis_length}" radius="${base_axis_radius}"/>
  <xacro:base_axis name="base_axis_back_left" length="${base_axis_length}" radius="${base_axis_radius}"/>
  <xacro:base_axis name="base_axis_back_right" length="${base_axis_length}" radius="${base_axis_radius}"/>

  <xacro:wheel name="wheel_front_left" radius="${wheel_radius}" width="${wheel_width}"/>
  <xacro:wheel name="wheel_front_right" radius="${wheel_radius}" width="${wheel_width}"/>
  <xacro:wheel name="wheel_back_left" radius="${wheel_radius}" width="${wheel_width}"/>
  <xacro:wheel name="wheel_back_right" radius="${wheel_radius}" width="${wheel_width}"/>

  <xacro:box name="indicator_box" parent_link="wheel_front_right"/>

  <joint name="joint_motor_front_left" type="fixed">
    <parent link="base_link"/>
    <child link="motor_front_left"/>
    <origin xyz="${-base_width / 2 + motor_length / 2} ${base_length / 2} 0" rpy="${pi/2} 0 ${pi}"/>
  </joint>

  <joint name="joint_motor_front_right" type="fixed">
    <parent link="base_link"/>
    <child link="motor_front_right"/>
    <origin xyz="${base_width / 2 - motor_length / 2} ${base_length / 2} 0" rpy="${-pi/2} 0 0"/>
  </joint>

  <joint name="joint_motor_back_left" type="fixed">
    <parent link="base_link"/>
    <child link="motor_back_left"/>
    <origin xyz="${-base_width / 2 + motor_length / 2} ${-base_length / 2} 0" rpy="${pi/2} 0 ${pi}"/>
  </joint>

  <joint name="joint_motor_back_right" type="fixed">
    <parent link="base_link"/>
    <child link="motor_back_right"/>
    <origin xyz="${base_width / 2 - motor_length / 2} ${-base_length / 2} 0" rpy="${-pi/2} 0 0"/>
  </joint>

  <joint name="joint_base_axis_front_left" type="continuous">
    <parent link="motor_front_left"/>
    <child link="base_axis_front_left"/>
    <origin xyz="${motor_length/2} 0 0" rpy="${-pi/2} 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <joint name="joint_base_axis_front_right" type="continuous">
    <parent link="motor_front_right"/>
    <child link="base_axis_front_right"/>
    <origin xyz="${motor_length/2} 0 0" rpy="${pi/2} 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <joint name="joint_base_axis_back_left" type="continuous">
    <parent link="motor_back_left"/>
    <child link="base_axis_back_left"/>
    <origin xyz="${motor_length/2} 0 0" rpy="${-pi/2} 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <joint name="joint_base_axis_back_right" type="continuous">
    <parent link="motor_back_right"/>
    <child link="base_axis_back_right"/>
    <origin xyz="${motor_length/2} 0 0" rpy="${pi/2} 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <joint name="joint_wheel_front_left" type="fixed">
    <parent link="base_axis_front_left"/>
    <child link="wheel_front_left"/>
    <origin xyz="${base_axis_length/2} 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="joint_wheel_front_right" type="fixed">
    <parent link="base_axis_front_right"/>
    <child link="wheel_front_right"/>
    <origin xyz="${base_axis_length/2} 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="joint_wheel_back_left" type="fixed">
    <parent link="base_axis_back_left"/>
    <child link="wheel_back_left"/>
    <origin xyz="${base_axis_length/2} 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="joint_wheel_back_right" type="fixed">
    <parent link="base_axis_back_right"/>
    <child link="wheel_back_right"/>
    <origin xyz="${base_axis_length/2} 0 0" rpy="0 0 0"/>
  </joint>

  <xacro:camera name="camera" width="${camera_width}" length="${camera_length}" height="${camera_height}" radius="${camera_lens_radius}"/>

  <joint name="joint_camera" type="fixed">
    <parent link="base_link"/>
    <child link="camera"/>
    <origin xyz="0 0 ${base_height}" rpy="${-pi/2} 0 0"/>
  </joint>

  <ros2_control name="FourWheelDriveSystem" type="system">
    <xacro:if value="${'$(arg sim_mode)' == 'gazebo'}">
      <hardware>
        <plugin>gazebo_ros2_control/GazeboSystem</plugin>
      </hardware>
    </xacro:if>
    <xacro:if value="${'$(arg sim_mode)' != 'gazebo'}">
      <hardware>
        <plugin>shelfbot/FourWheelDriveController</plugin>
      </hardware>
    </xacro:if>
    <joint name="joint_base_axis_front_left">
      <command_interface name="position"/>
      <state_interface name="position"/>
    </joint>
    <joint name="joint_base_axis_front_right">
      <command_interface name="position"/>
      <state_interface name="position"/>
    </joint>
    <joint name="joint_base_axis_back_left">
      <command_interface name="position"/>
      <state_interface name="position"/>
    </joint>
    <joint name="joint_base_axis_back_right">
      <command_interface name="position"/>
      <state_interface name="position"/>
    </joint>
  </ros2_control>

</robot>
