<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="shelfbot">

  <!-- Include common properties and entities -->
  <xacro:include filename="$(find shelfbot)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/motor.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/wheel.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/camera.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/fixed_joint.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/revolute_joint.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/base_axis.xacro"/>

  <!-- Base Footprint Link -->
  <link name="base_footprint"/>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
      <material name="golden_brown"/>
    </visual>
  </link>

  <xacro:fixed_joint name="joint_base_footprint" parent="base_footprint" child="base_link" origin_xyz="0 0 ${base_height / 2}" origin_rpy="0 0 0"/>

  <!-- Base Axes -->
  <xacro:base_axis name="base_axis_front_left" length="${base_axis_length}" radius="${base_axis_radius}"/>
  <xacro:base_axis name="base_axis_front_right" length="${base_axis_length}" radius="${base_axis_radius}"/>
  <xacro:base_axis name="base_axis_back_left" length="${base_axis_length}" radius="${base_axis_radius}"/>
  <xacro:base_axis name="base_axis_back_right" length="${base_axis_length}" radius="${base_axis_radius}"/>

  <!-- Base Axes Joints -->
  <xacro:fixed_joint name="joint_base_axis_front_left" parent="base_link" child="base_axis_front_left" origin_xyz="${-base_width / 2} ${base_length / 2} 0" origin_rpy="0 ${pi/2} 0"/>
  <xacro:fixed_joint name="joint_base_axis_front_right" parent="base_link" child="base_axis_front_right" origin_xyz="${base_width / 2} ${base_length / 2} 0" origin_rpy="0 ${pi/2} 0"/>
  <xacro:fixed_joint name="joint_base_axis_back_left" parent="base_link" child="base_axis_back_left" origin_xyz="${-base_width / 2} ${-base_length / 2} 0" origin_rpy="0 ${pi/2} 0"/>
  <xacro:fixed_joint name="joint_base_axis_back_right" parent="base_link" child="base_axis_back_right" origin_xyz="${base_width / 2} ${-base_length / 2} 0" origin_rpy="0 ${pi/2} 0"/>

  <!-- Motors -->
  <xacro:motor name="motor_front_left" length="${motor_length}" radius="${motor_radius}" mass="1.0" ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
  <xacro:motor name="motor_front_right" length="${motor_length}" radius="${motor_radius}" mass="1.0" ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
  <xacro:motor name="motor_back_left" length="${motor_length}" radius="${motor_radius}" mass="1.0" ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
  <xacro:motor name="motor_back_right" length="${motor_length}" radius="${motor_radius}" mass="1.0" ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>

  <!-- Motor Joints -->
  <xacro:fixed_joint name="joint_motor_front_left" parent="base_axis_front_left" child="motor_front_left" origin_xyz="0 0 0" origin_rpy="0 0 0"/>
  <xacro:fixed_joint name="joint_motor_front_right" parent="base_axis_front_right" child="motor_front_right" origin_xyz="0 0 0" origin_rpy="0 0 0"/>
  <xacro:fixed_joint name="joint_motor_back_left" parent="base_axis_back_left" child="motor_back_left" origin_xyz="0 0 0" origin_rpy="0 0 0"/>
  <xacro:fixed_joint name="joint_motor_back_right" parent="base_axis_back_right" child="motor_back_right" origin_xyz="0 0 0" origin_rpy="0 0 0"/>

  <!-- Wheels -->
  <xacro:wheel name="wheel_front_left" radius="${wheel_radius}" width="${wheel_width}"/>
  <xacro:wheel name="wheel_front_right" radius="${wheel_radius}" width="${wheel_width}"/>
  <xacro:wheel name="wheel_back_left" radius="${wheel_radius}" width="${wheel_width}"/>
  <xacro:wheel name="wheel_back_right" radius="${wheel_radius}" width="${wheel_width}"/>

  <!-- Wheels Joints -->
  <xacro:fixed_joint name="joint_wheel_front_left" parent="base_axis_front_left" child="wheel_front_left" origin_xyz="0 0 -${motor_length/2}" origin_rpy="0 0 0"/>
  <xacro:fixed_joint name="joint_wheel_front_right" parent="base_axis_front_right" child="wheel_front_right" origin_xyz="0 0 ${motor_length/2}" origin_rpy="0 0 0"/>
  <xacro:fixed_joint name="joint_wheel_back_left" parent="base_axis_back_left" child="wheel_back_left" origin_xyz="0 0 -${motor_length/2}" origin_rpy="0 0 0"/>
  <xacro:fixed_joint name="joint_wheel_back_right" parent="base_axis_back_right" child="wheel_back_right" origin_xyz="0 0 ${motor_length/2}" origin_rpy="0 0 0"/>

  <!-- Camera -->
  <xacro:camera name="camera" width="${camera_width}" length="${camera_length}" height="${camera_height}" radius="${camera_lens_radius}"/>

  <!-- Camera Joint -->
  <xacro:fixed_joint name="joint_camera" parent="base_link" child="camera" origin_xyz="0 0 ${base_height}" origin_rpy="0 0 0"/>

</robot>
