<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="ultrasonic_sensor" params="name">
    <!-- Main link for the sensor, positioned at the center of the PCB -->
    <link name="${name}">
      <visual>
        <!-- The main blue PCB -->
        <geometry>
          <box size="${ultrasonic_pcb_x_size} ${ultrasonic_pcb_y_size} ${ultrasonic_pcb_z_size}"/>
        </geometry>
        <material name="blue"/>
      </visual>
      <collision>
        <geometry>
          <box size="${ultrasonic_pcb_x_size} ${ultrasonic_pcb_y_size} ${ultrasonic_collision_z_size}"/> <!-- Collision box covers the whole volume -->
        </geometry>
      </collision>
      <inertial>
        <mass value="${ultrasonic_mass}"/>
        <xacro:box_inertia m="${ultrasonic_mass}" x="${ultrasonic_pcb_x_size}" y="${ultrasonic_pcb_y_size}" z="${ultrasonic_collision_z_size}"/>
      </inertial>
    </link>

    <!-- Visual representation of the two silver transducers -->
    <link name="${name}_transducer_1">
      <visual>
        <origin xyz="0 0 ${ultrasonic_transducer_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${ultrasonic_transducer_radius}" length="${ultrasonic_transducer_length}"/>
        </geometry>
        <material name="light_grey"/>
      </visual>
    </link>

    <link name="${name}_transducer_2">
      <visual>
        <origin xyz="0 0 ${ultrasonic_transducer_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${ultrasonic_transducer_radius}" length="${ultrasonic_transducer_length}"/>
        </geometry>
        <material name="light_grey"/>
      </visual>
    </link>

    <!-- Fixed joints to attach the transducers to the main sensor link -->
    <joint name="joint_${name}_transducer_1" type="fixed">
      <parent link="${name}"/>
      <child link="${name}_transducer_1"/>
      <origin xyz="${ultrasonic_transducer_x_offset} 0 0" rpy="0 0 0"/> <!-- Position one transducer -->
    </joint>

    <joint name="joint_${name}_transducer_2" type="fixed">
      <parent link="${name}"/>
      <child link="${name}_transducer_2"/>
      <origin xyz="-${ultrasonic_transducer_x_offset} 0 0" rpy="0 0 0"/> <!-- Position the other transducer -->
    </joint>

  </xacro:macro>

</robot>
