controller_manager:
  ros__parameters:
    update_rate: 2 # Hz

    four_wheel_drive_controller:
      type: shelfbot/FourWheelDriveController
      ros__parameters:
        joints:
          - joint_base_axis_front_left
          - joint_base_axis_front_right
          - joint_base_axis_back_left
          - joint_base_axis_back_right

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    hardware_interface:
      type: shelfbot/FourWheelDriveHardwareInterface
      communication_type: "microros"

four_wheel_drive_controller:
  ros__parameters:
    # Kinematic parameters used by the controller
    joint_names:
      - joint_base_axis_front_left
      - joint_base_axis_front_right
      - joint_base_axis_back_left
      - joint_base_axis_back_right
    
    front_left_joint_names: ["joint_base_axis_front_left"]
    back_left_joint_names: ["joint_base_axis_back_left"]
    front_right_joint_names: ["joint_base_axis_front_right"]
    back_right_joint_names: ["joint_base_axis_back_right"]

    wheel_separation: 0.50
    wheel_radius: 0.075

    # Command velocity timeout
    cmd_vel_timeout: 0.5 # seconds

    # Corrects for a fixed orientation error in the odometry calculation.
    odometry_yaw_correction_degrees: -90.0

    # Robot dimensions (for URDF and other nodes)
    base_width: 0.45
    base_length: 0.55
    base_height: 0.02
    base_mass: 50.0

    motor_radius: 0.05
    motor_length: 0.1
    motor_mass: 2.0

    wheel_width: 0.05
    wheel_mass: 5.0

    camera_width: 0.02
    camera_length: 0.02
    camera_height: 0.01
    camera_lens_radius: 0.005
    camera_mount_height: 0.5
    camera_mass: 0.5

    base_axis_radius: 0.02
    base_axis_length: 0.175  
    base_axis_mass: 2.0

    gear_ratio: 1

    # Box parameters
    box_x_size: 0.05
    box_y_size: 0.05
    box_z_size: 0.1
    box_mass: 0.1
    box_inertia: 0.000083

    # Ultrasonic sensor parameters
    ultrasonic_pcb_x_size: 0.045
    ultrasonic_pcb_y_size: 0.020
    ultrasonic_pcb_z_size: 0.002
    ultrasonic_collision_z_size: 0.015
    ultrasonic_mass: 0.01
    ultrasonic_transducer_radius: 0.008
    ultrasonic_transducer_length: 0.015
    ultrasonic_transducer_x_offset: 0.0125
    ultrasonic_z_offset: 0.01

    # Joint dynamics
    joint_damping: 0.1
    joint_friction: 0.1
