controller_manager:
  ros__parameters:
    update_rate: 2 # Hz

    four_wheel_drive_controller:
      type: shelfbot/FourWheelDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

four_wheel_drive_controller:
  ros__parameters:
    # Kinematic parameters used by the controller
    joint_names:
      - joint_base_axis_front_left
      - joint_base_axis_back_left
      - joint_base_axis_back_right
      - joint_base_axis_front_right
    
    front_left_joint_names: ["joint_base_axis_front_left"]
    back_left_joint_names: ["joint_base_axis_back_left"]
    front_right_joint_names: ["joint_base_axis_front_right"]
    back_right_joint_names: ["joint_base_axis_back_right"]

    wheel_separation: 0.45
    wheel_radius: 0.075

    # Command velocity timeout
    cmd_vel_timeout: 0.5 # seconds

    # Robot dimensions (for URDF and other nodes)
    base_width: 0.45
    base_length: 0.55
    base_height: 0.02
    base_mass: 50.0

    motor_radius: 0.05
    motor_length: 0.1
    motor_mass: 2.0

    wheel_width: 0.05
    wheel_mass: 5.0

    camera_width: 0.02
    camera_length: 0.02
    camera_height: 0.01
    camera_lens_radius: 0.05
    camera_mount_height: 0.5
    camera_mass: 0.5

    base_axis_radius: 0.02
    base_axis_length: 0.25  
    base_axis_mass: 2.0

    gear_ratio: 1