controller_manager:
  ros__parameters:
    update_rate: 20 # Hz
    use_sim_time: true

    four_wheel_drive_controller:
      type: shelfbot/FourWheelDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

four_wheel_drive_controller:
  ros__parameters:
    use_joint_state_broadcaster: true

    update_rate: 20 # Hz
    publish_rate: 1.0

    enable_odom_tf: true
    open_loop: false

    base_frame_id: base_footprint
    odom_frame_id: odom

    # Kinematic parameters
    joint_names:
      - joint_base_axis_front_left
      - joint_base_axis_back_left
      - joint_base_axis_back_right
      - joint_base_axis_front_right
    
    front_left_joint_names: ["joint_base_axis_front_left"]
    back_left_joint_names: ["joint_base_axis_back_left"]
    front_right_joint_names: ["joint_base_axis_front_right"]
    back_right_joint_names: ["joint_base_axis_back_right"]

    wheel_separation: 0.45
    wheel_radius: 0.075

    # Command topic and timeout
    cmd_vel_timeout: 0.5 # seconds

    # Velocity and acceleration limits
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 1.0 # m/s
    linear.x.min_velocity: -1.0 # m/s
    linear.x.max_acceleration: 0.5 # m/s^2
    linear.x.min_acceleration: -0.5 # m/s^2

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 1.57 # rad/s
    angular.z.min_velocity: -1.57 # rad/s
    angular.z.max_acceleration: 0.5 # rad/s^2
    angular.z.min_acceleration: -0.5 # rad/s^2