
gazebo:
  physics:
    type: ode
    max_step_size: 0.001
    real_time_factor: 1.0
    real_time_update_rate: 1000.0
  gravity:
    x: 0.0
    y: 0.0
    z: -9.81
  world:
    max_contacts: 20

robot:
  base_link:
    mass: 5.0
    inertia:
      ixx: 0.1
      iyy: 0.1
      izz: 0.1
  wheel:
    mass: 0.5
    inertia:
      ixx: 0.001
      iyy: 0.001
      izz: 0.001
  motor:
    mass: 0.3
    inertia:
      ixx: 0.0001
      iyy: 0.0001
      izz: 0.0001

joints:
  wheel_joint:
    damping: 0.1
    friction: 0.1
    limit:
      lower: -1.57
      upper: 1.57
      velocity: 10
      effort: 10
