# Shelfbot Nav2 Parameters for Camera-Only Dynamic Navigation

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      lookahead_dist: 1.0
      min_lookahead_dist: 0.5
      max_lookahead_dist: 2.0
      lookahead_time: 1.5
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.1
      regulated_linear_scaling_min_radius: 0.5
      use_cost_regulated_linear_velocity_scaling: false
      allow_reversing: false
      max_robot_pose_search_dist: 10.0
      wheel_base: 0.45
      tread: 0.45
      max_angular_vel: 1.0
      max_linear_vel: 0.5
      min_linear_vel: 0.0
        
planner_server:
  ros__parameters:
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false

behavior_server:
  ros__parameters:
    use_sim_time: False
    costmap_topic: "local_costmap/costmap_raw"
    footprint_topic: "local_costmap/published_footprint"
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    global_frame: "odom"
    robot_base_frame: "base_footprint"

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: odom
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_round_robin_node_bt_node
    bt_xml_filename: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    
local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: "base_footprint"
      update_frequency: 5.0
      publish_frequency: 2.0
      width: 10
      height: 10
      robot_radius: 0.3 # Approximate radius of the robot
      transform_tolerance: 0.5
      plugins: ["voxel_layer", "inflation_layer"]
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_unknown_space: False
        observation_sources: "pointcloud"
        pointcloud:
          sensor_frame: camera_link # Or whatever your camera's frame is
          data_type: "PointCloud2"
          topic: "/rtabmap/obstacles" # The topic RTAB-Map publishes obstacles on
          marking: true
          clearing: true
          min_obstacle_height: 0.05
          max_obstacle_height: 1.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55

global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: "base_footprint"
      update_frequency: 1.0
      publish_frequency: 1.0
      transform_tolerance: 0.5
      # Make the global costmap a rolling window that moves with the robot
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: false
        map_subscribe_transient_local: True
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: "pointcloud"
        pointcloud:
          sensor_frame: camera_link
          data_type: "PointCloud2"
          topic: "/rtabmap/obstacles"
          marking: true
          clearing: true
          min_obstacle_height: 0.05
          max_obstacle_height: 1.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55

map_server:
  ros__parameters:
    use_sim_time: False
    # We are not using a static map, so we use the default empty map.
    # Nav2 still requires this server to be running.
    yaml_filename: ""

lifecycle_manager:
  ros__parameters:
    use_sim_time: False
    autostart: True
    node_names:
      - planner_server
      - controller_server
      - smoother_server
      - behavior_server
      - bt_navigator
      - waypoint_follower
      - map_server