<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="shelfbot">

  <xacro:include filename="$(find shelfbot)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/motor.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/wheel.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/camera.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/fixed_joint.xacro"/>
  <xacro:include filename="$(find shelfbot)/urdf/revolute_joint.xacro"/>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
  </link>

  <xacro:motor name="motor_front_left" length="${motor_length}" radius="${motor_radius}" mass="1.0" ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
  <xacro:motor name="motor_front_right" length="${motor_length}" radius="${motor_radius}" mass="1.0" ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
  <xacro:motor name="motor_back_left" length="${motor_length}" radius="${motor_radius}" mass="1.0" ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
  <xacro:motor name="motor_back_right" length="${motor_length}" radius="${motor_radius}" mass="1.0" ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>

  <xacro:fixed_joint name="joint_motor_front_left" parent="base_link" child="motor_front_left" origin_width="-${base_width / 2}" origin_length="${base_length / 2}" origin_height="0"/>
  <xacro:fixed_joint name="joint_motor_front_right" parent="base_link" child="motor_front_right" origin_width="${base_width / 2}" origin_length="${base_length / 2}" origin_height="0"/>
  <xacro:fixed_joint name="joint_motor_back_left" parent="base_link" child="motor_back_left" origin_width="-${base_width / 2}" origin_length="-${base_length / 2}" origin_height="0"/>
  <xacro:fixed_joint name="joint_motor_back_right" parent="base_link" child="motor_back_right" origin_width="${base_width / 2}" origin_length="-${base_length / 2}" origin_height="0"/>

  <xacro:wheel name="wheel_front_left" radius="${wheel_radius}" width="${wheel_width}"/>
  <xacro:wheel name="wheel_front_right" radius="${wheel_radius}" width="${wheel_width}"/>
  <xacro:wheel name="wheel_back_left" radius="${wheel_radius}" width="${wheel_width}"/>
  <xacro:wheel name="wheel_back_right" radius="${wheel_radius}" width="${wheel_width}"/>

  <xacro:fixed_joint name="joint_wheel_front_left" parent="motor_front_left" child="wheel_front_left" origin_width="0" origin_length="0" origin_height="${motor_length}"/>
  <xacro:fixed_joint name="joint_wheel_front_right" parent="motor_front_right" child="wheel_front_right" origin_width="0" origin_length="0" origin_height="${motor_length}"/>
  <xacro:fixed_joint name="joint_wheel_back_left" parent="motor_back_left" child="wheel_back_left" origin_width="0" origin_length="0" origin_height="${motor_length}"/>
  <xacro:fixed_joint name="joint_wheel_back_right" parent="motor_back_right" child="wheel_back_right" origin_width="0" origin_length="0" origin_height="${motor_length}"/>

  <xacro:camera name="camera" width="${camera_width}" length="${camera_length}" height="${camera_height}" radius="${camera_lens_radius}"/>

  <xacro:fixed_joint name="joint_camera" parent="base_link" child="camera" origin_width="0" origin_length="0" origin_height="${base_height}"/>

</robot>