#!/usr/bin/env python3
"""
scripts/read_zip_log.py
=======================
Parse and inspect shelfbot_zip.log  (generated by shelfbot::log_zip).

Log line format (post-fix):
  [<13-digit-epoch_ms>][<MODULE>:<TAG>] k=v,k=v,...

The parser also handles pre-fix logs where multiple records were fused onto
one physical line (missing newline bug) by scanning for the record-start
boundary pattern rather than treating each physical line as one record.

Usage
-----
  # Stream live (tail -f style)
  python3 read_zip_log.py --follow

  # Filter to odometry and hardware events
  python3 read_zip_log.py --module ODO HW

  # Show only the last N seconds
  python3 read_zip_log.py --since 30

  # Show odometry trajectory as CSV
  python3 read_zip_log.py --module ODO --tag UPD --csv

  # Detect health gaps (micro-ROS silent > N ms)
  python3 read_zip_log.py --health-gap 500

  # Show lifecycle event summary
  python3 read_zip_log.py --lifecycle

Examples of useful event sequences to look for
-----------------------------------------------
  CTRL:GOAL → CTRL:TMO          command received then timed out
  HW:INIT   → HW:ACT            normal bring-up
  UROS:OPEN → UROS:POS(first=1) first firmware packet
  UROS:GAP                       firmware dropped packets
  ODO:LATCH → ODO:UPD           odometry online
  HW:RD(hlth=0)                  read while comms unhealthy
"""

import argparse
import re
import sys
import time
from pathlib import Path

# ── Parser ────────────────────────────────────────────────────────────────────

# Matches a record boundary anywhere in a string.
# Epoch is exactly 13 digits (valid from year 2001 to 2286).
# KV body captured lazily so multiple fused records on one physical line
# are all found by findall().
_RECORD_RE = re.compile(
    r'\[(\d{13})\]'                  # epoch_ms
    r'\[([A-Z0-9_]{1,8})'           # MODULE
    r':([A-Z0-9_]{1,8})\]'          # TAG
    r'[ \t]*([^\[]*?)'              # KV body — up to next '[' or end
    r'(?=\[\d{13}\]|\Z)',           # lookahead: next record OR end of string
    re.DOTALL,
)

def parse_kv(raw: str) -> dict:
    """Parse  k=v,k=v,...  into a dict of str -> float|str."""
    out = {}
    for part in raw.replace('\n', '').split(','):
        part = part.strip()
        if '=' not in part:
            continue
        k, _, v = part.partition('=')
        k = k.strip()
        v = v.strip()
        try:
            out[k] = float(v)
        except ValueError:
            out[k] = v
    return out

def records_from_text(text: str):
    """Yield (epoch_ms, module, tag, kv_dict) from a block of text.
    Handles both normal (one record per line) and fused (pre-fix) files."""
    for m in _RECORD_RE.finditer(text):
        epoch_ms = int(m.group(1))
        module   = m.group(2)
        tag      = m.group(3)
        kv       = parse_kv(m.group(4))
        yield epoch_ms, module, tag, kv

# ── Log path ──────────────────────────────────────────────────────────────────

def default_log_path() -> Path:
    return Path.home() / '.ros' / 'log' / 'shelfbot_zip.log'

# ── Reporters ─────────────────────────────────────────────────────────────────

LIFECYCLE_TAGS = {'INIT', 'CFG', 'ACT', 'DEACT', 'EXPO', 'EXPC', 'OPEN', 'CLOSE'}

def fmt_time(epoch_ms: int) -> str:
    t = epoch_ms / 1000.0
    return time.strftime('%H:%M:%S', time.localtime(t)) + f'.{epoch_ms % 1000:03d}'

def fmt_kv(kv: dict) -> str:
    parts = []
    for k, v in kv.items():
        if isinstance(v, float):
            # Trim trailing zeros but keep at least one decimal
            s = f'{v:.4f}'.rstrip('0').rstrip('.')
            parts.append(f'{k}={s}')
        else:
            parts.append(f'{k}={v}')
    return '  '.join(parts)

def print_event(epoch_ms, module, tag, kv, *, csv_mode=False):
    if csv_mode:
        vals = ','.join(
            f'{k}={v:.6g}' if isinstance(v, float) else f'{k}={v}'
            for k, v in kv.items()
        )
        print(f'{epoch_ms},{module},{tag},{vals}')
    else:
        ts = fmt_time(epoch_ms)
        print(f'{ts}  {module:<6s}:{tag:<6s}  {fmt_kv(kv)}')

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description='shelfbot_zip.log reader')
    ap.add_argument('--log',        default=str(default_log_path()),
                    help='Path to shelfbot_zip.log (default: %(default)s)')
    ap.add_argument('--follow',     action='store_true',
                    help='Stream new lines as they arrive (like tail -f)')
    ap.add_argument('--module',     nargs='*',
                    help='Filter by module(s): ODO HW CTRL UROS')
    ap.add_argument('--tag',        nargs='*',
                    help='Filter by tag(s): UPD TF GOAL INIT ACT ...')
    ap.add_argument('--since',      type=float, default=0,
                    help='Show only events from the last N seconds')
    ap.add_argument('--csv',        action='store_true',
                    help='Output as CSV (epoch_ms,module,tag,k=v,...)')
    ap.add_argument('--health-gap', type=float, default=0, metavar='MS',
                    help='Report UROS:POS gaps longer than N ms')
    ap.add_argument('--lifecycle',  action='store_true',
                    help='Print lifecycle event summary only')
    args = ap.parse_args()

    log_path = Path(args.log)
    if not log_path.exists():
        print(f'[read_zip_log] Log not found: {log_path}', file=sys.stderr)
        print('[read_zip_log] Run the robot first, or pass --log <path>',
              file=sys.stderr)
        sys.exit(1)

    module_filter = {m.upper() for m in args.module} if args.module else None
    tag_filter    = {t.upper() for t in args.tag}    if args.tag    else None

    cutoff_ms = int((time.time() - args.since) * 1000) if args.since > 0 else 0

    last_uros_pos_ms = None
    gap_threshold_ms = args.health_gap
    lc_events        = []   # (epoch_ms, module, tag, kv)

    def handle(epoch_ms, module, tag, kv):
        nonlocal last_uros_pos_ms

        if cutoff_ms and epoch_ms < cutoff_ms:
            return
        if module_filter and module not in module_filter:
            return
        if tag_filter and tag not in tag_filter:
            return

        # Health-gap detector
        if gap_threshold_ms > 0 and module == 'UROS' and tag == 'POS':
            if last_uros_pos_ms is not None:
                gap = epoch_ms - last_uros_pos_ms
                if gap > gap_threshold_ms:
                    print(f'{fmt_time(epoch_ms)}  *** UROS GAP {gap} ms ***')
            last_uros_pos_ms = epoch_ms

        # Lifecycle summary
        if args.lifecycle:
            if tag in LIFECYCLE_TAGS:
                lc_events.append((epoch_ms, module, tag, kv))
            return

        print_event(epoch_ms, module, tag, kv, csv_mode=args.csv)

    # ── Read file ─────────────────────────────────────────────────────────────
    with open(log_path, 'r', errors='replace') as f:
        if not args.follow:
            # Read entire file at once; regex handles fused lines
            text = f.read()
            for rec in records_from_text(text):
                handle(*rec)
        else:
            # Follow mode: process complete lines, buffer partials
            print(f'[read_zip_log] Following {log_path} ...', file=sys.stderr)
            buf = ''
            while True:
                chunk = f.read(4096)
                if chunk:
                    buf += chunk
                    # Process all complete records in buf
                    matches = list(_RECORD_RE.finditer(buf))
                    if matches:
                        # Keep tail from last match start (may be incomplete)
                        last_end = matches[-1].end()
                        for m in matches:
                            handle(int(m.group(1)), m.group(2), m.group(3),
                                   parse_kv(m.group(4)))
                        buf = buf[last_end:]
                else:
                    time.sleep(0.05)

    if args.lifecycle and lc_events:
        print(f'\n{"═"*64}')
        print(' LIFECYCLE EVENT SUMMARY')
        print(f'{"═"*64}')
        prev_ms = None
        for epoch_ms, module, tag, kv in lc_events:
            ts  = fmt_time(epoch_ms)
            dt  = '' if prev_ms is None else f'  (+{epoch_ms - prev_ms} ms)'
            print(f'{ts}  {module:<6s}:{tag:<6s}  {fmt_kv(kv)}{dt}')
            prev_ms = epoch_ms
        print(f'\nTotal lifecycle events: {len(lc_events)}')

if __name__ == '__main__':
    main()
